// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api.proto

// package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

package api

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KafkaSubEvent int32

const (
	KafkaSubEvent_Nothing KafkaSubEvent = 0
	KafkaSubEvent_Push    KafkaSubEvent = 1
	KafkaSubEvent_Sub     KafkaSubEvent = 2
)

var KafkaSubEvent_name = map[int32]string{
	0: "Nothing",
	1: "Push",
	2: "Sub",
}

var KafkaSubEvent_value = map[string]int32{
	"Nothing": 0,
	"Push":    1,
	"Sub":     2,
}

func (x KafkaSubEvent) String() string {
	return proto.EnumName(KafkaSubEvent_name, int32(x))
}

func (KafkaSubEvent) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type Message struct {
	PlayerId             int64    `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	Ops                  int32    `protobuf:"varint,2,opt,name=Ops,proto3" json:"Ops,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return m.Size()
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("publisher.service.v1.KafkaSubEvent", KafkaSubEvent_name, KafkaSubEvent_value)
	proto.RegisterType((*Message)(nil), "publisher.service.v1.Message")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xc1, 0x4a, 0xc3, 0x30,
	0x1c, 0xc6, 0x97, 0x75, 0xba, 0x19, 0x15, 0x4b, 0x10, 0x99, 0x55, 0xca, 0xf0, 0x34, 0x04, 0x53,
	0x54, 0xf0, 0x01, 0xc4, 0x1d, 0x86, 0xa8, 0x65, 0xbb, 0x79, 0x4b, 0x66, 0x96, 0x86, 0x75, 0x49,
	0x68, 0x92, 0xc2, 0xde, 0xc4, 0x47, 0xda, 0xd1, 0x47, 0xd0, 0xfa, 0x22, 0xd2, 0x74, 0xd3, 0x93,
	0xb7, 0xef, 0xcb, 0xf7, 0x23, 0xfc, 0x7f, 0x70, 0x8f, 0x68, 0x81, 0x75, 0xa1, 0xac, 0x42, 0xc7,
	0xda, 0xd1, 0x5c, 0x98, 0x8c, 0x15, 0xd8, 0xb0, 0xa2, 0x14, 0x33, 0x86, 0xcb, 0xeb, 0xe8, 0x8a,
	0x0b, 0x9b, 0x39, 0x8a, 0x67, 0x6a, 0x99, 0x70, 0xc5, 0x55, 0xe2, 0x61, 0xea, 0xe6, 0xbe, 0xf9,
	0xe2, 0x53, 0xf3, 0x49, 0x74, 0xc6, 0x95, 0xe2, 0x39, 0xfb, 0xa3, 0xd8, 0x52, 0xdb, 0xd5, 0x66,
	0x3c, 0xdf, 0x8c, 0x44, 0x8b, 0x84, 0x48, 0xa9, 0x2c, 0xb1, 0x42, 0x49, 0xd3, 0xac, 0x17, 0x8f,
	0xb0, 0xfb, 0xc4, 0x8c, 0x21, 0x9c, 0xa1, 0x08, 0xf6, 0xd2, 0x9c, 0xac, 0x58, 0x31, 0x7e, 0xeb,
	0x83, 0x01, 0x18, 0x06, 0x93, 0xdf, 0x8e, 0x42, 0x18, 0xbc, 0x68, 0xd3, 0x6f, 0x0f, 0xc0, 0x70,
	0x67, 0x52, 0x47, 0x84, 0x60, 0xe7, 0x81, 0x58, 0xd2, 0x0f, 0x06, 0x60, 0x78, 0x30, 0xf1, 0xf9,
	0x32, 0x81, 0x87, 0x0b, 0x32, 0x5f, 0x90, 0xa9, 0xa3, 0xa3, 0x92, 0x49, 0x8b, 0xf6, 0x61, 0xf7,
	0x59, 0xd9, 0x4c, 0x48, 0x1e, 0xb6, 0x50, 0x0f, 0x76, 0x52, 0x67, 0xb2, 0x10, 0xa0, 0x2e, 0x0c,
	0xa6, 0x8e, 0x86, 0xed, 0x9b, 0x31, 0x3c, 0x4a, 0xb7, 0xfe, 0xb5, 0x3e, 0x2b, 0xd0, 0x1d, 0xec,
	0xa4, 0x42, 0x72, 0x74, 0x82, 0x9b, 0xbb, 0xf1, 0x56, 0x0a, 0x8f, 0x6a, 0xa9, 0xe8, 0x9f, 0xf7,
	0xfb, 0xd3, 0xf5, 0x57, 0xdc, 0x5a, 0x57, 0x31, 0xf8, 0xa8, 0x62, 0xf0, 0x59, 0xc5, 0xe0, 0xfd,
	0x3b, 0x6e, 0xbd, 0x06, 0x44, 0x0b, 0xba, 0xeb, 0xd1, 0xdb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x38, 0x08, 0x14, 0x95, 0x77, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PublisherserverClient is the client API for Publisherserver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PublisherserverClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type publisherserverClient struct {
	cc *grpc.ClientConn
}

func NewPublisherserverClient(cc *grpc.ClientConn) PublisherserverClient {
	return &publisherserverClient{cc}
}

func (c *publisherserverClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/publisher.service.v1.Publisherserver/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublisherserverServer is the server API for Publisherserver service.
type PublisherserverServer interface {
	Ping(context.Context, *empty.Empty) (*empty.Empty, error)
}

// UnimplementedPublisherserverServer can be embedded to have forward compatible implementations.
type UnimplementedPublisherserverServer struct {
}

func (*UnimplementedPublisherserverServer) Ping(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterPublisherserverServer(s *grpc.Server, srv PublisherserverServer) {
	s.RegisterService(&_Publisherserver_serviceDesc, srv)
}

func _Publisherserver_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherserverServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/publisher.service.v1.Publisherserver/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherserverServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Publisherserver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "publisher.service.v1.Publisherserver",
	HandlerType: (*PublisherserverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Publisherserver_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintApi(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Ops != 0 {
		i = encodeVarintApi(dAtA, i, uint64(m.Ops))
		i--
		dAtA[i] = 0x10
	}
	if m.PlayerId != 0 {
		i = encodeVarintApi(dAtA, i, uint64(m.PlayerId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintApi(dAtA []byte, offset int, v uint64) int {
	offset -= sovApi(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PlayerId != 0 {
		n += 1 + sovApi(uint64(m.PlayerId))
	}
	if m.Ops != 0 {
		n += 1 + sovApi(uint64(m.Ops))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovApi(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApi(x uint64) (n int) {
	return sovApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerId", wireType)
			}
			m.PlayerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlayerId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ops", wireType)
			}
			m.Ops = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ops |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApi
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApi
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApi
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApi        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApi          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApi = fmt.Errorf("proto: unexpected end of group")
)
